name: Sync Fork

on:
  schedule:
    - cron: '*/30 * * * *'
  push:
  
  workflow_dispatch:

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.4
        with:
          token: ${{ secrets.SYNC_TOKEN }}
          owner: pycord
          base: master
          head: master
